env:
  browser: true
  es6: true
  worker: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

parser:
  "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2020
  sourceType: module

plugins:
  - "@typescript-eslint"

root:
  true

globals:
  Elm: readonly
  MediaMetadata: readonly
  RemoteStorage: readonly
  tocca: readonly

rules:
  "@typescript-eslint/ban-ts-comment":
    0

  no-cond-assign:
    0

  no-unexpected-multiline:
    0

  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
