name: ongaku-ryoho
version: 1.0.0


default-extensions:
  - ExtendedDefaultRules
  - NoImplicitPrelude
  - OverloadedStrings


dependencies:
  - aeson == 1.1.*
  - base >= 4.7 && < 5
  - binary == 0.8.*
  - bytestring == 0.10.*
  - cmark == 0.5.*
  - directory == 1.3.*
  - flow == 1.*
  - http-types == 0.9.*
  - process == 1.4.*
  - protolude == 0.1.*
  - shikensu == 0.3.*
  - text == 1.*
  - unordered-containers == 0.2.*
  - wai == 3.2.*
  - wai-app-static == 3.1.*
  - wai-cors == 0.2.*
  - warp == 3.2.*


executables:
  # ðŸšœ
  build:
    main: Main.hs
    source-dirs:
      - src
      - system/Build

  # ðŸ”
  server:
    main: Main.hs
    source-dirs: system/Server

  # ðŸª
  vendor:
    main: Main.hs
    source-dirs: system/Vendor
