module Tracks.ContextMenu exposing (..)

import ContextMenu.Types exposing (..)
import Date exposing (Date)
import Material.Icons.Action as Icons
import Material.Icons.Content as Icons
import Material.Icons.Editor as Icons
import Mouse
import Playlists.Types exposing (Msg(..))
import Playlists.Utils
import Queue.Types
import Queue.Utils
import Sources.Types exposing (Source)
import Tracks.Types exposing (..)
import Tracks.Utils
import Types as TopLevel exposing (..)
import Variables exposing (colorDerivatives)


trackMenu : Tracks.Types.Model -> Maybe String -> List IdentifiedTrack -> List Source -> Date -> Mouse.Position -> ContextMenu TopLevel.Msg
trackMenu model lastModifiedPlaylist identifiedTracks sources timestamp =
    let
        tracks =
            List.map Tracks.Utils.unindentify identifiedTracks
    in
        [ queueActions identifiedTracks

        -- Playlist actions
        --
        , case model.selectedPlaylist of
            Just selectedPlaylist ->
                if selectedPlaylist.autoGenerated then
                    -- Playlist actions, default.
                    defaultPlaylistActions tracks lastModifiedPlaylist
                else
                    -- Playlist actions, when in a playlist.
                    [ ( Icons.format_list_numbered colorDerivatives.text 14
                      , "Remove from playlist"
                      , identifiedTracks
                            |> List.map (Tuple.first >> .indexInPlaylist >> Maybe.withDefault 0)
                            |> RemoveTracksByIndex selectedPlaylist.name
                            |> PlaylistsMsg
                      )
                    , ( Icons.format_list_numbered colorDerivatives.text 14
                      , "Add to another playlist"
                      , RequestAssistanceForPlaylists tracks
                      )
                    ]

            Nothing ->
                -- Playlist actions, default.
                defaultPlaylistActions tracks lastModifiedPlaylist

        -- Track URL
        --
        , if List.length identifiedTracks == 1 then
            [ ( Icons.link colorDerivatives.text 14
              , "Copy short-lived url"
              , identifiedTracks
                    |> List.head
                    |> Maybe.map (Queue.Utils.makeEngineItem timestamp sources)
                    |> Maybe.map .url
                    |> Maybe.withDefault "<missing-track>"
                    |> CopyToClipboard
              )
            ]
          else
            []
        ]
            |> List.concat
            |> ContextMenu



-- Actions


defaultPlaylistActions : List Track -> Maybe String -> ContextMenuItems TopLevel.Msg
defaultPlaylistActions tracks lastModifiedPlaylist =
    case lastModifiedPlaylist of
        Just playlistName ->
            [ ( Icons.format_list_numbered colorDerivatives.text 14
              , "Add to \"" ++ playlistName ++ "\""
              , tracks
                    |> List.map Playlists.Utils.playlistTrackFromTrack
                    |> AddToPlaylist playlistName
                    |> PlaylistsMsg
              )
            , ( Icons.format_list_numbered colorDerivatives.text 14
              , "Add to another playlist"
              , RequestAssistanceForPlaylists tracks
              )
            ]

        Nothing ->
            [ ( Icons.format_list_numbered colorDerivatives.text 14
              , "Add to playlist"
              , RequestAssistanceForPlaylists tracks
              )
            ]


queueActions : List IdentifiedTrack -> ContextMenuItems TopLevel.Msg
queueActions identifiedTracks =
    case identifiedTracks of
        [ a ] ->
            [ ( Icons.event_seat colorDerivatives.text 14
              , "Play next"
              , QueueMsg (Queue.Types.InjectFirst a { showNotification = True })
              )
            , ( Icons.event_seat colorDerivatives.text 14
              , "Add to queue"
              , QueueMsg (Queue.Types.InjectLast [ a ] { showNotification = True })
              )
            ]

        list ->
            [ ( Icons.event_seat colorDerivatives.text 14
              , "Add to queue"
              , QueueMsg (Queue.Types.InjectLast list { showNotification = True })
              )
            ]
