module Playlists.Encoding exposing (..)

import Json.Decode as Decode
import Json.Encode as Encode
import Playlists.Types exposing (..)


-- Encode


encodePlaylist : Playlist -> Encode.Value
encodePlaylist playlist =
    Encode.object
        [ ( "autoGenerated", Encode.bool playlist.autoGenerated )
        , ( "name", Encode.string playlist.name )
        , ( "tracks", Encode.list (List.map Encode.string playlist.tracks) )
        ]



-- Decode


playlistDecoder : Decode.Decoder Playlist
playlistDecoder =
    Decode.map3 Playlist
        (Decode.field "autoGenerated" Decode.bool)
        (Decode.field "name" Decode.string)
        (Decode.field "tracks" <| Decode.list Decode.string)
