module Playlists.Encoding exposing (..)

import Json.Decode as Decode
import Json.Encode as Encode
import Playlists.Types exposing (..)


-- Encode


encode : Playlist -> Encode.Value
encode playlist =
    Encode.object
        [ ( "autoGenerated", Encode.bool playlist.autoGenerated )
        , ( "name", Encode.string playlist.name )
        , ( "tracks", Encode.list (List.map encodePlaylistTrack playlist.tracks) )
        ]


encodePlaylistTrack : PlaylistTrack -> Encode.Value
encodePlaylistTrack playlistTrack =
    Encode.object
        [ ( "album", Encode.string playlistTrack.album )
        , ( "artist", Encode.string playlistTrack.artist )
        , ( "title", Encode.string playlistTrack.title )
        ]



-- Decode


decoder : Decode.Decoder Playlist
decoder =
    Decode.map3 Playlist
        (Decode.field "autoGenerated" Decode.bool)
        (Decode.field "name" Decode.string)
        (Decode.field "tracks" <| Decode.list playlistTrackDecoder)


playlistTrackDecoder : Decode.Decoder PlaylistTrack
playlistTrackDecoder =
    Decode.map3 PlaylistTrack
        (Decode.field "album" Decode.string)
        (Decode.field "artist" Decode.string)
        (Decode.field "title" Decode.string)
