module Playlists.Types exposing (..)

-- Playlist


type alias Playlist =
    { autoGenerated : Bool
    , name : String
    , tracks : List PlaylistTrack
    }


type alias PlaylistTrack =
    { album : String
    , artist : String
    , title : String
    }


type alias IdentifiedPlaylistTrack =
    ( Identifiers, PlaylistTrack )


type alias Identifiers =
    { index : Int
    }



-- Messages


type Msg
    = SetCollection (List Playlist)
      -- Addition
    | AddToPlaylist String (List PlaylistTrack)
      -- Creation
    | CreateFromForm
    | CreateWithTracks String (List PlaylistTrack)
    | SetNewPlaylistName String
      -- Modification
    | UpdatePlaylist Playlist
    | UpdatePlaylistName Playlist
      -- Removal
    | Remove String
    | RemoveTracksByIndex String (List Int)



-- Model


type alias Model =
    { collection : List Playlist
    , lastModifiedPlaylist : Maybe String
    , newPlaylist : Playlist
    }



-- Pages


type Page
    = Edit String
    | Index
    | New
