module Playlists.Types exposing (..)

-- Playlist


type alias Playlist =
    { autoGenerated : Bool
    , name : String
    , tracks : List String
    }



-- Messages


type Msg
    = SetCollection (List Playlist)



-- Model


type alias Model =
    { collection : List Playlist
    }



-- Pages


type Page
    = Index
    | New
